sudo: false

services: couchdb

language:
- node_js
- ruby
- python

node_js: 8
rvm: ruby-head
python: 2.7

cache:
  directories:
  - node_modules
  - ~/.rvm/gems
  - ~/.local

addons:
  hosts:
    - auth.local
    - cassandre.local
    - couchdb.local
    - xcouchdb.local
    - xxcouchdb.local
    - xxxcouchdb.local
    - auth_fixed.local
    - auth_ldap.local
    - auth_http.local

install:
- npm install
- cp conf/config.sample.json conf/config.json
- mkdir log/
- touch log/misc.log
- npm start
# Install CouchApp
- pip install --user couchapp
# Install Capybara
- gem install capybara-webkit rspec
# Install Cassandre
- curl -X PUT -d '"false"' localhost:5984/_config/httpd/secure_rewrites
- curl -X PUT localhost:5984/cassandre
- wget https://github.com/Hypertopic/Cassandre/archive/v2.zip
- unzip v2.zip
- couchapp push Cassandre-2 http://localhost:5984/cassandre
# Set up test fixture
- curl -X PUT -d '"{couch_httpd_auth, cookie_authentication_handler}, {couch_httpd_auth, proxy_authentication_handler}, {couch_httpd_auth, default_authentication_handler}"' localhost:5984/_config/httpd/authentication_handlers
- curl -X PUT -d'"true"' localhost:5984/_config/couch_httpd_auth/proxy_use_secret
- curl -X PUT -d'"secretkeyforcouchdbauthtoken"' localhost:5984/_config/couch_httpd_auth/secret
- curl -X PUT localhost:5984/cassandre/iamlate -d '{"corpus":"Wonderland", "name":"I am late"}'
- curl -X PUT localhost:5984/_users/org.couchdb.user:hatter -H 'Accept:application/json' -H 'Content-Type:application/json' -d '{"name":"hatter", "password":"teaparty", "roles":[], "type":"user"}'
- curl -X PUT localhost:5984/_config/admins/carroll -d '"curiouser"'
script:
- jasmine-node spec/api/
- xvfb-run rspec spec/features/*
